spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update 
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/cafe_management
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.security.user.name=admin
spring.security.user.password=123456

spring.servlet.multipart.max-file-size=50MB   
spring.servlet.multipart.max-request-size=50MB

# Thời gian tối đa (ms) hệ thống chờ để mượn 1 kết nối từ pool (20 giây)
spring.datasource.hikari.connection-timeout=20000

# Số lượng kết nối rảnh rỗi (idle) tối thiểu luôn được giữ trong pool
spring.datasource.hikari.minimum-idle=5

# Số lượng kết nối tối đa trong pool (Bao gồm cả đang hoạt động và rảnh rỗi)
spring.datasource.hikari.maximum-pool-size=20

# Thời gian tối đa (ms) 1 kết nối được phép nằm rảnh trước khi bị thu hồi (5 phút)
spring.datasource.hikari.idle-timeout=300000

# Thời gian sống tối đa (ms) của 1 kết nối trong pool để tránh lỗi tràn bộ nhớ (20 phút)
spring.datasource.hikari.max-lifetime=1200000